### ISSUE TITLE
Add release/tag and dependencies version

### ISSUE THREAD

**Issue by Warvito** [brudfors/UniRes#15]
Hi Mikael,

Congratulation on the great repository! I just wanted to make some suggestions; please, consider using Github tags or releases. It would make it easier to follow the latest updates/fixes of the tool. Also, it would be great to have specified the nitorch version that the unires uses to avoid having recent nitorch updates break any function from unires. Finally, it would be great to see the unires available at pypi to be easier to install and define it in the requirements. I would be more than happy to help with any of these suggestions; just let me know what you think. Cheers

**Comment by balbasty** [comment]
Hi Mikael,

You could start by explicitly listing nitorch as a (github) dependency in your setup.py and pin it to a specific commit that you know works well with UniRes. Some pointers here: https://stackoverflow.com/questions/55146691
I would also add [all] at the end of the URL so that all optional dependencies to nitorch are installed (nibabel, etc). 

Happy to help with this ;)

**Comment by brudfors** [comment]
Hi @Warvito 

Sorry this took ages, but I just pushed a branch that should sort out the dependency issue:

https://github.com/brudfors/UniRes/tree/fix-dependencies

Could you maybe try this, when you have the time, and let me know if it works for you?

I will then make a PR and merge it into main. Then I will create a release tag, as requested :)

**Comment by brudfors** [comment]
Also @Warvito, if you are happy to help me get UniRes onto pypi, that would be great!

**Comment by brudfors** [comment]
Hi @Warvito, 

@balbasty managed to test the changes that I made to the setup.py and it all worked on the GPU. Therefore, I created a release tag:

https://github.com/brudfors/UniRes/releases/tag/v0.1

Hope it is helps :)
